---
#TODO check if nignx with certbot will work in container only
# http://nginx.org/en/docs/beginners_guide.html
# https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
# https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/
# https://www.ssllabs.com/ssltest/analyze.html



- name: Checkout nginx repository
  git:
    force: yes
    repo: "{{ git_url }}"
    dest: "{{ application_directory }}"


- name: Copy nginx configuration
  template:
    src: default.conf
    dest: "{{ application_directory }}/data/nginx/app.conf"
- name: Copy letsencrypt
  template:
    src: init-letsencrypt.sh
    dest: "{{ application_directory }}/init-letsencrypt.sh"
