---

- name: Be sure base packages are installed
  apt:
    autoremove: yes
    name:
      - htop
      - telnet
      - ntp
      - zsh
      - software-properties-common
      - vim
      - screen
      - curl
      - ldap-utils
    state: latest
    update_cache: yes
    cache_valid_time: 3600
